name: .NET Core 2.0

on:
  push:
    branches: [ 2.0.0 ]
  pull_request:
    branches: [ 2.0.0 ]

jobs:
  build:

    runs-on: [self-hosted, windows]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Setup Nuget
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Restore Packages
      run: nuget restore CedMod.sln
    - name: Build
      run: dotnet build --configuration Debug --no-restore CedMod.sln
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
       name: CedMod Build Results
       path: ${{ github.workspace }}/bin/Debug/CedMod*
    - name: Upload1
      uses: actions/upload-artifact@v2
      with:
        name: Build References
        path: ${{ github.workspace }}/bin/Debug/

